from enum import Enum


class Tags(Enum):
    PSYCHIATRIST_NOT_NEEDED = 'психиатр не нужен'
    SPEECH_THERAPIST_NEUROPSYCHOLOGIST = 'логопед/нейропсихолог'
    PSYCHIATRIST = 'психиатр'
    BIPOLAR_DISORDER = 'БАР'
    CHILDHOOD_AUTISM = 'детский аутизм'
    BORDERLINE_PERSONALITY_DISORDER = 'ПРЛ'
    IMPULSIVITY = 'импульсивность'
    GRIEF = 'горе'
    ANOREXIA = 'анорексия'
    BINGE_EATING = 'переедание'
    NARCISSISTIC_PERSONALITY_DISORDER = 'НРЛ'
    OCD = 'ОКР'
    SOCIAL_PHOBIA = 'социофобия'
    ANXIETY = 'тревога'
    DEPRESSION = 'депрессия'
    CHRONIC_PAIN = 'хроническая боль'
    PSYCHOSOMATICS = 'психосоматика'
    GAMBLING = 'гэмблинг'
    TRAUMA = 'травма'
    ENURESIS_ENCOPRESIS = 'энурез/энкопрез'
    BURNOUT = 'выгорание'
    ASD = 'нейроотличия, РАС'
    ADHD = 'СДВГ'
    ADDICTIONS = 'зависимости'
    DYSMORPHOPHOBIA = 'дисморфофобия'
    SELF_HARM_SUICIDE = 'селфхарм/суицид'
    OVERTHINKING = 'сверхконтроль'
    SEXOLOGY = 'сексология'
    SOMNOLOGY = 'сомнология'
    REBT = 'РЭПТ'
    RELATIONSHIPS = 'отношения'
    FAMILY_THERAPY = 'семейная терапия'
    PSYCHODYNAMIC_THERAPY = 'психодинамическая терапия'
    EMOTIONAL_REGULATION = 'эмоциональная регуляция'
    COACHING = 'коучинг'
    GERONTOLOGIST = 'геронтолог'
    ACT = 'АСТ'
    PSYCHOANALYSIS = 'психоанализ'
    SCHEMA_THERAPY = 'схема-терапия'
    VIOLENCE_PERPETRATORS = 'авторы насилия'
    SUPERVISOR = 'супервизор'
    GROUP_THERAPY = 'групповая терапия'
    EMIGRATION = 'эмиграция'
