"""empty message

Revision ID: 13137a712283
Revises: 9f2c1a4d7b11
Create Date: 2026-04-26 20:42:17.877656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13137a712283'
down_revision: Union[str, Sequence[str], None] = '9f2c1a4d7b11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_requests', sa.Column('is_approved', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_requests', 'is_approved')
    # ### end Alembic commands ###
