"""

Revision ID: 30bf3e52d2d6
Revises: 
Create Date: 2026-01-25 11:16:28.663294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30bf3e52d2d6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('problem_description', sa.String(), nullable=False),
    sa.Column('sex', sa.Enum('male', 'female', name='sex'), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('currency_amount', sa.JSON(), nullable=False),
    sa.Column('psychotherapist_sex', sa.Enum('male', 'female', name='sex'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_requests')
    # ### end Alembic commands ###
