"""empty message

Revision ID: 4d1b05920ca0
Revises: c1d3f3075fd3
Create Date: 2026-02-03 13:59:52.634853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d1b05920ca0'
down_revision: Union[str, Sequence[str], None] = 'c1d3f3075fd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_request_therapists',
    sa.Column('therapist_id', sa.BigInteger(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('percentage_of_compliance', sa.Float(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['client_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['therapist_id'], ['therapists.tg_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('therapist_id', 'request_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_request_therapists')
    # ### end Alembic commands ###
