"""empty message

Revision ID: 566e2c203de6
Revises: dc4787e132c5
Create Date: 2026-05-11 13:00:11.320834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '566e2c203de6'
down_revision: Union[str, Sequence[str], None] = 'dc4787e132c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client_requests', 'client_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client_requests', 'client_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
