"""

Revision ID: 5ad85f4096ba
Revises: c8dbf9957887
Create Date: 2026-01-27 18:11:08.255942

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5ad85f4096ba'
down_revision: str | Sequence[str] | None = 'c8dbf9957887'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queue', sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queue', 'finished_at')
    # ### end Alembic commands ###
