"""

Revision ID: 75fbc373e8b3
Revises: 5ad85f4096ba
Create Date: 2026-01-27 20:29:18.469642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75fbc373e8b3'
down_revision: Union[str, Sequence[str], None] = '5ad85f4096ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_requests', sa.Column('need_psychiatrist', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_requests', 'need_psychiatrist')
    # ### end Alembic commands ###
