"""empty message

Revision ID: 7e20a624b18d
Revises: c48b8500a47a
Create Date: 2026-04-20 22:01:50.901722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e20a624b18d'
down_revision: Union[str, Sequence[str], None] = 'c48b8500a47a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE therapiststatuses AS ENUM ('no_questionary', 'not_approved', 'approved', 'have_questionary');")
    op.add_column('therapists', sa.Column('status', sa.Enum('no_questionary', 'not_approved', 'approved', 'have_questionary', name='therapiststatuses'), server_default='no_questionary', nullable=False));
    op.alter_column('therapists', 'age',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('therapists', 'experience',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('therapists', 'min_client_age',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('therapists', 'max_client_age',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('therapists', 'max_client_age',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('therapists', 'min_client_age',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('therapists', 'experience',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('therapists', 'age',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('therapists', 'status')
    # ### end Alembic commands ###
