"""empty message

Revision ID: a69a6c3ec9fe
Revises: 88d81acdf433
Create Date: 2026-01-30 20:49:24.046081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a69a6c3ec9fe'
down_revision: Union[str, Sequence[str], None] = '88d81acdf433'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('therapists',
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('photo', sa.String(), nullable=True),
    sa.Column('approved', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('consent', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('pitch', sa.String(length=350), nullable=True),
    sa.Column('site', sa.String(length=100), nullable=True),
    sa.Column('sex', sa.Enum('male', 'female', name='sex', native_enum=False), nullable=True),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('experience', sa.Integer(), nullable=False),
    sa.Column('count_of_recomendations', sa.Integer(), server_default='0', nullable=False),
    sa.Column('min_client_age', sa.Integer(), nullable=False),
    sa.Column('max_client_age', sa.Integer(), nullable=False),
    sa.Column('online', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('currency_amount', sa.JSON(), nullable=False),
    sa.Column('contacts_for_client', sa.String(length=150), nullable=True),
    sa.Column('psychiatrist', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('group_therapy', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('supervisor', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('gerontologist', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('couple_therapist', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('available_to_call', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('tg_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('therapists')
    # ### end Alembic commands ###
