"""empty message

Revision ID: c1d3f3075fd3
Revises: a69a6c3ec9fe
Create Date: 2026-01-30 20:56:47.464760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1d3f3075fd3'
down_revision: Union[str, Sequence[str], None] = 'a69a6c3ec9fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('therapists_tags',
    sa.Column('therapist_id', sa.BigInteger(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['therapist_id'], ['therapists.tg_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('therapist_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('therapists_tags')
    # ### end Alembic commands ###
