"""

Revision ID: e1d451f78343
Revises: b57c1cd44ca3
Create Date: 2026-01-25 13:50:17.698089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1d451f78343'
down_revision: Union[str, Sequence[str], None] = 'b57c1cd44ca3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('queue',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('READY', 'DONE', 'ERROR', name='queuestatus'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('queue')
    # ### end Alembic commands ###
