"""empty message

Revision ID: f65f9174511d
Revises: 566e2c203de6
Create Date: 2026-07-11 10:16:51.951269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f65f9174511d'
down_revision: Union[str, Sequence[str], None] = '566e2c203de6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('therapists', sa.Column('username', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('therapists', 'username')
    # ### end Alembic commands ###
