"""empty message

Revision ID: f65f9174511d
Revises: 566e2c203de6
Create Date: 2026-07-11 10:16:51.951269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f65f9174511d'
down_revision: Union[str, Sequence[str], None] = '566e2c203de6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('username', sa.String(), nullable=False))
    op.drop_constraint(op.f('admin_login_key'), 'admin', type_='unique')
    op.create_unique_constraint(None, 'admin', ['username'])
    op.drop_column('admin', 'login')
    op.add_column('therapists', sa.Column('username', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('therapists', 'username')
    op.add_column('admin', sa.Column('login', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'admin', type_='unique')
    op.create_unique_constraint(op.f('admin_login_key'), 'admin', ['login'], postgresql_nulls_not_distinct=False)
    op.drop_column('admin', 'username')
    # ### end Alembic commands ###
