"""empty message

Revision ID: fb477d919cb0
Revises: 4d1b05920ca0
Create Date: 2026-02-07 11:15:07.410773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb477d919cb0'
down_revision: Union[str, Sequence[str], None] = '4d1b05920ca0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('therapists', 'couple_therapist')
    op.drop_column('therapists', 'supervisor')
    op.drop_column('therapists', 'gerontologist')
    op.drop_column('therapists', 'group_therapy')
    op.drop_column('therapists', 'psychiatrist')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('therapists', sa.Column('psychiatrist', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('therapists', sa.Column('group_therapy', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('therapists', sa.Column('gerontologist', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('therapists', sa.Column('supervisor', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('therapists', sa.Column('couple_therapist', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
